= TILs (Today I Learned)
:toc:


== Overview

Various tidbits learned (TILs), inspired by https://github.com/charliegerard[@charliegerard]'s link:https://github.com/charliegerard/dev-notes[repo]!


== Categories

=== Build tools

- link:docs/build-tools/gradle-build-scans.adoc[Gradle build scans]

=== Technical Infrastructure

- link:docs/tech-infra/ldap.adoc[LDAP]

=== Technical Architecture

Software design and architecture related learnings, philosophies, considerations, viewpoints, and so on.

- link:docs/tech-architecture/lock-in.adoc[Evaluating "lock-in"]
- link:docs/tech-architecture/decision-making-options.adoc[Decision making - buying and selling options]
- link:docs/tech-architecture/decision-framework.adoc[Decision making framework]
- link:docs/tech-architecture/solid-principles.adoc[SOLID principles]
- link:docs/tech-architecture/yagni.adoc[Yagni]

=== Product Management

Product management/ownership/design related learnings.

- link:docs/product-mgmt/naming-features.adoc[Naming features]

=== Miscellaneous

Other lessons such as inter-personal, business related, etc.

- link:docs/miscellaneous/negotiation.adoc[Negotiation]
- link:docs/miscellaneous/flip-the-script.adoc[Selling your idea - "Flip the Script"]


== Disclaimer

_**Most learnings and content are directly derived or taken from other places.
Links are usually provided to the source.
The intention is to highlight areas of interest, content generally not intended to be considered the author's original work by any means.**_
