= What is Architecture

Hodgepodge of points from admirable speakers such as Gregor Hohpe and Martin Fowler:

- Architects are concerned with the "non-requirements", the non-functional things like scalability, reliability, maintainability, etc.
- Nobody cares about your architecture - it's invisible.
- Architecture focuses on the "hidden design", i.e. the quality of the software, the modularization, the layers of abstraction.
- When arguing for focusing on quality over "quantity" i.e. features, arguing that we need to "do a good job" i.e. craftsmanship, will always lose to economics i.e. business value, cost reduction, etc.
- Architects must visit all floors of the organization; "ride the architect elevator", where they can understand the business strategy and explain the importance of architecture and design to business leads, while also understanding the inner workings in the "engine room", the engineering.
- Architecture is about "selling options" (see other TIL).
We pay a price up-front for the *option* or ability to exercise a certain decision or build in the future, presumably at a favorable cost.
