= Selling stuff - "Flip the Script"

Summary from blinks on the book, which outlines how, as a 'salesperson', to convince people that your idea is their own.

== Key messages
- "People only listen to you if they think you're an equal." 
Hence you should raise yourself to the same status as the person you are talking to.
- "Establish your credibility quickly and unquestionably." 
Easy way to do this is via a 'flash roll', where you quickly (60-90 seconds) provide detailed, technical information on the matter to provey our expertise.
- "Addressing pre-wired ideas allow us to anticipate and satisfy questions before they're all asked."
The main pre-wired ideas are 1) the threat or why they should care, 2) the reward or what they get out of it, and 3) fairness or your equal investment in the opportunity.
- "Frame your proposal in terms the client is already familiar with." 
Highlight how what you're selling is 'the new normal', by describing it in familiar terms and comparing to existing, known alternatives.
- "Leverage pessimism." 
Establish your expertise by showing you've dealt with this before, outline the obvious and less obvious downsides to address them up-front, then hand over to the client indirectly e.g. "That's what I would do."
You can also have the client focus by highlighting the key deciding factors you want them to focus on.
- "Be true and authentic to yourself."
Smart buyers see through inauthenticity, and it makes them question you.

== Summary
Selling ideas and points of views can be achieved by flipping the script, controlling the conversation and establishing your credibility.
